// packages/web/src/components/MarketCard.svelte
<script lang="ts">
	import type { MarketWithOdds } from "@wpm/shared";
	import * as Card from "$lib/components/ui/card/index.js";
	import { Badge } from "$lib/components/ui/badge/index.js";
	import { Separator } from "$lib/components/ui/separator/index.js";

	let { market }: { market: MarketWithOdds } = $props();

	const statusConfig = {
		open: { variant: "default" as const, label: "Live" },
		closed: { variant: "secondary" as const, label: "Closed" },
		resolved: { variant: "outline" as const, label: "Resolved" },
		cancelled: { variant: "destructive" as const, label: "Cancelled" },
	};

	let status = $derived(statusConfig[market.status]);
	let isResolved = $derived(market.status === "resolved");
</script>

<Card.Root>
	<Card.Header class="flex flex-row items-start justify-between gap-4">
		<Card.Title class="text-base">{market.name}</Card.Title>
		<Card.Action>
			<Badge variant={status.variant}>{status.label}</Badge>
		</Card.Action>
	</Card.Header>
	<Card.Content class="flex flex-col gap-0">
		<div
			class="flex items-center justify-between py-3"
			class:text-foreground={!isResolved || market.result === "A"}
			class:text-muted-foreground={isResolved && market.result !== "A"}
		>
			<span class="font-medium">{market.outcomes[0]}</span>
			<div class="flex items-center gap-4">
				<span class="text-sm tabular-nums">{Math.round(market.priceA * 100)}%</span>
				<span class="text-sm font-semibold tabular-nums">&times;{market.multiplierA.toFixed(2)}</span>
			</div>
		</div>
		<Separator />
		<div
			class="flex items-center justify-between py-3"
			class:text-foreground={!isResolved || market.result === "B"}
			class:text-muted-foreground={isResolved && market.result !== "B"}
		>
			<span class="font-medium">{market.outcomes[1]}</span>
			<div class="flex items-center gap-4">
				<span class="text-sm tabular-nums">{Math.round(market.priceB * 100)}%</span>
				<span class="text-sm font-semibold tabular-nums">&times;{market.multiplierB.toFixed(2)}</span>
			</div>
		</div>
	</Card.Content>
</Card.Root>

// apps/web/src/components/market-card.tsx
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { LiveOdds } from "@/components/live-odds";
import type { MarketWithOdds } from "@wpm/shared";

export function MarketCard({ market }: { market: MarketWithOdds }) {
  const closesAt = new Date(market.closesAt);
  const now = new Date();
  const isClosingSoon = closesAt.getTime() - now.getTime() < 60 * 60 * 1000;

  return (
    <Card className="flex flex-col">
      <CardHeader className="pb-3">
        <CardTitle className="font-mono text-sm font-bold leading-snug">{market.name}</CardTitle>
      </CardHeader>
      <CardContent className="flex-1">
        <LiveOdds
          marketId={market.id}
          outcomes={market.outcomes}
          initialPriceA={market.priceA}
          initialPriceB={market.priceB}
        />
      </CardContent>
      <CardFooter className="justify-between text-xs text-muted-foreground">
        <span className="font-mono tabular-nums">
          {market.bettorCount} {market.bettorCount === 1 ? "bettor" : "bettors"}
        </span>
        <span className={isClosingSoon ? "text-destructive" : ""}>{formatCloseTime(closesAt)}</span>
      </CardFooter>
    </Card>
  );
}

function formatCloseTime(date: Date): string {
  const now = new Date();
  const diff = date.getTime() - now.getTime();

  if (diff <= 0) return "Closed";

  const hours = Math.floor(diff / (1000 * 60 * 60));
  const mins = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));

  if (hours >= 24) {
    const days = Math.floor(hours / 24);
    return `${days}d left`;
  }

  if (hours > 0) return `${hours}h ${mins}m left`;
  return `${mins}m left`;
}
