// apps/web/src/components/balance.tsx
"use client";

import { useBalance } from "@/lib/realtime/useBalance";

export function Balance({ balance, userId }: { balance: number; userId: string }) {
  useBalance(userId);

  return (
    <span className="font-mono text-sm tabular-nums">
      {balance.toLocaleString()} <span className="text-muted-foreground">WPM</span>
    </span>
  );
}

// packages/web/src/components/balance.svelte
<script lang="ts">
	import { balance } from "$lib/stores/balance.svelte.js";
</script>

{#if balance.value !== null}
	<span class="text-sm font-medium tabular-nums text-foreground">
		{balance.value.toLocaleString()} WPM
	</span>
{:else}
	<span class="text-sm text-muted-foreground">Loading...</span>
{/if}
