// apps/web/src/app/(auth)/auth/verify/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { useState, useEffect } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { authClient } from "@/lib/auth/client";

type Stage = "verifying" | "passkey-prompt" | "error";

export default function VerifyPage() {
  const router = useRouter();
  const { data: session } = authClient.useSession();
  const [stage, setStage] = useState<Stage>("verifying");
  const [enrolling, setEnrolling] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (stage !== "verifying") return;

    if (session?.user) {
      setStage("passkey-prompt");
      return;
    }

    const timeout = setTimeout(() => {
      if (!session?.user) setStage("error");
    }, 3000);

    return () => clearTimeout(timeout);
  }, [session, stage]);

  async function addPasskey() {
    setEnrolling(true);
    setError(null);
    try {
      const { error: authError } = await authClient.passkey.addPasskey({
        name: "WPM Passkey",
      });
      if (authError) throw new Error(authError.message);
    } catch {
      // Passkey enrollment is optional — swallow errors
    } finally {
      router.push("/");
    }
  }

  function skip() {
    router.push("/");
  }

  if (stage === "verifying") {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Verifying…</CardTitle>
          <CardDescription>Completing your sign-in</CardDescription>
        </CardHeader>
      </Card>
    );
  }

  if (stage === "error") {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Verification failed</CardTitle>
          <CardDescription>
            We couldn&apos;t verify your sign-in. The link may have expired.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Button variant="outline" className="w-full" onClick={() => router.push("/login")}>
            Back to login
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Set up a passkey</CardTitle>
        <CardDescription>
          Use Touch ID, Face ID, or your device biometrics for faster sign-in next time.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-3">
        {error && <p className="text-sm text-destructive">{error}</p>}
        <Button onClick={addPasskey} disabled={enrolling} className="w-full">
          {enrolling ? "Setting up…" : "Add passkey"}
        </Button>
        <Button variant="ghost" onClick={skip} disabled={enrolling} className="w-full">
          Skip for now
        </Button>
      </CardContent>
    </Card>
  );
}

// packages/web/src/routes/auth/verify/+page.svelte
<script lang="ts">
	import { goto } from "$app/navigation";
	import { authClient } from "$lib/auth-client.js";
	import { session } from "$lib/stores/auth.svelte.js";
	import { Button } from "$lib/components/ui/button/index.js";
	import * as Card from "$lib/components/ui/card/index.js";
	import { onMount } from "svelte";

	let status = $state<"verifying" | "passkey-prompt" | "done" | "error">("verifying");
	let error = $state<string | null>(null);
	let addingPasskey = $state(false);

	onMount(async () => {
		await new Promise((r) => setTimeout(r, 500));

		const current = session.get();
		if (current?.data?.user) {
			status = "passkey-prompt";
		} else {
			status = "error";
			error = "Verification failed. Please try again.";
		}
	});

	async function addPasskey() {
		addingPasskey = true;
		try {
			const { error: passkeyError } = await authClient.passkey.addPasskey({
				name: "WPM Passkey",
			});
			if (passkeyError) throw new Error(passkeyError.message);
		} catch {
			// Passkey is optional — don't block the user
		} finally {
			addingPasskey = false;
			goto("/");
		}
	}

	function skipPasskey() {
		goto("/");
	}
</script>

<div class="flex min-h-[60vh] items-center justify-center">
	<Card.Root class="w-full max-w-sm">
		{#if status === "verifying"}
			<Card.Header>
				<Card.Title>Verifying...</Card.Title>
				<Card.Description>Confirming your login link.</Card.Description>
			</Card.Header>
		{:else if status === "passkey-prompt"}
			<Card.Header>
				<Card.Title>You're in!</Card.Title>
				<Card.Description>
					Want to add a passkey for faster logins? You can use Touch ID, Face ID, or your device's
					biometrics.
				</Card.Description>
			</Card.Header>
			<Card.Content class="flex flex-col gap-3">
				<Button onclick={addPasskey} disabled={addingPasskey}>
					{addingPasskey ? "Setting up..." : "Add passkey"}
				</Button>
				<Button variant="ghost" onclick={skipPasskey}>Skip for now</Button>
			</Card.Content>
		{:else if status === "error"}
			<Card.Header>
				<Card.Title>Something went wrong</Card.Title>
				<Card.Description>{error}</Card.Description>
			</Card.Header>
			<Card.Content>
				<a href="/login">
					<Button variant="outline" class="w-full">Back to login</Button>
				</a>
			</Card.Content>
		{:else}
			<Card.Header>
				<Card.Title>Welcome to WPM!</Card.Title>
				<Card.Description>Redirecting...</Card.Description>
			</Card.Header>
		{/if}
	</Card.Root>
</div>
